services:
  - type: worker
    name: drm-downloader-bot
    env: python
    plan: free
    buildCommand: |
      curl -L https://github.com/nilaoda/N_m3u8DL-RE/releases/latest/download/N_m3u8DL-RE_Linux_x64.tar.gz | tar xz
      chmod +x N_m3u8DL-RE
      mv N_m3u8DL-RE /usr/local/bin/
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
        
